### ISSUE TITLE
Documentation for Registered Versions

### ISSUE THREAD

**Issue by cortner** [ACEsuit/Polynomials4ML.jl#31]
Can somebody figure out how to make TagBot trigger doc builds for registered versions?

**Comment by cortner** [comment]
@tjjarvinen  --  have you done this before? If yes, I'd be grateful if you can look into it. I just checked again and it looks like I have everything set up correctly but the tagbot is not triggering the doc build, so obviously I'm still missing something.

**Comment by tjjarvinen** [comment]
Doc builds should trigger when you tag a version. So, basically TagBot will tag a release version, which will trigger Doc build. It seems that this has not happened. So the issue is should be on CI.yml file. This point is the key
 https://github.com/ACEsuit/Polynomials4ML.jl/blob/955f4f06c776e7a6554eefd7a6fb5ea83c453530/.github/workflows/CI.yml#L6C1-L6C16

```yml
on:
  push:
    branches:
      - main
    tags: ['*']
```

But for me it looks like ok - I have been using

```yml
on:
  push:
    branches:
      - master
    tags: '*'
```

So, the next option would be to look for GitHub Actions log on what is going.

But I have not use TagBot myself, so I am not much help here.
